= Handling Errors in Javascript UDFs
:description: Error handling in Javascript user-defined functions use the same standard exception mechanism as part of the language standard.
:page-pagination: prev
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2

[abstract]
{description}

Runtime errors that occur during the execution of an {sqlpp} statement are usually handled by the runtime, which will return a JSON object giving details of the error. 
For example, if we execute a record insertion function with a key that already exists:

[source, n1ql]
----
EXECUTE FUNCTION AddAirlineWithDate(1220, 'Raz Air', 'RAZ-AIR', 'United Kingdom');
----

If the key already exists, then an error object is returned:

[source, json]
----
include::example$javascript-udfs/duplicate-key-error.json5[]
----

In most cases, it's a lot better if the Javascript function itself can handle errors that are likely to occur. 
This gives the developer the option of responding with a more user-friendly message, or taking an alternative course of action.

The following function will add an airline record, but will return an `failure` message if the attempt isn't successful.

[source, javascript]
----
include::example$javascript-udfs/add-airline-with-check.js[]
----

If the record key already exists, then calling this method with `EXECUTE FUNCTION`  will produce the following result:

[source, json]
----
[
  "failure"
]
----

== Further Reading

include::partial$javascript-udfs/further-reading.adoc[tags="query-workbench;select;execute-function"]
